# This workflow build .NET Core application.

name: Build

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '.github/**'
      - 'docs/**'
      - 'README.md'
      - 'LICENSE'
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest
    
    env:
      Solution_Name: UniCheatNET.sln
      BuildBinDir: ${{ github.workspace }}\bin
      Configuration: ${{ matrix.configuration }}

    steps:
    - name: Cache
      uses: actions/cache@v4.2.0
      with:
        path: obj
        key: obj
              
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Restore, build the application
      run: dotnet build -c $env:Configuration $env:Solution_Name /p:Configuration=$env:Configuration

    - name: Upload build artifacts
      id: artifact-upload-step
      uses: actions/upload-artifact@v4
      with:
        name: ${{env.Configuration}}.zip
        path: ${{env.BuildBinDir}}\${{env.Configuration}}
        if-no-files-found: error


